include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
    - lib/**.config.dart
    - lib/**.gr.dart
    - lib/localization/generated/
    - lib/**/__generated__/
    - lib/**/example_env.dart
    - lib/localization/**
  errors:
    invalid_annotation_target: ignore
    require_trailing_commas: ignore
    unused_import: error
linter:
  rules:
    avoid_print: true # Uncomment to disable the `avoid_print` rule
    prefer_single_quotes: true # Uncomment to enable the `prefer_single_quotes` rule
    sort_constructors_first: true
    prefer_const_constructors: true
    public_member_api_docs: false
    sort_pub_dependencies: ignore
    always_specify_types: true
    lines_longer_than_80_chars: false
    use_key_in_widget_constructors: true
    unrelated_type_equality_checks: true
    require_trailing_commas: true
    use_enums: true
    unawaited_futures: true
    invalid_case_patterns: true
    avoid_returning_null_for_void: true
    camel_case_extensions: true
    cascade_invocations: true
    always_declare_return_types: true
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
 